---
title: "20210423 4단원문제"
author: "김승건"
date: '2021 4 23 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1부터 100까지의 수 중에서 3의 배수이면서 4의 배수는 아닌 수의 합을 구하라


```{r}
x <- c(1:100)
x1 <- x[x%%3==0]

y <- c(1:100)
y1 <- y[y%%4==0]

diffx <- setdiff(x1, y1)
diffx

sum(diffx)
```

# x와 n입력하면 1부터 n까지의 수 중에서 x의 배수 합을 구해주는 사용자 정의 함수를 만들어라

```{r}
fn = function(x, n){
    sum <- 0
    for ( i in 1:n) {
        if (i %% x == 0) {
            sum <- sum + i
        }
    }
    return(sum)
}
fn(3,10)
```

# intall.

```{r}
library(hflights) # 라이브러리추가
sum(is.na(hflights))
```

# hflights 데이터에서 비행시간이 가장 긴 데이터는 몇 시간 몇 분인가

```{r}
max(is.na(hflights$AirTime))
airT <- na.omit(hflights$AirTime)
airH <- max(airT) %/% 60
airM <- max(airT) %% 60
print(paste0(airH, 'h'))
```
```{r}
max(is.na(hflights$AirTime))
airT <- na.omit(hflights$AirTime)
airH <- max(airT) %/% 60
airM <- max(airT) %% 60
print(paste0(airM, 'm'))
```

# hflights 데이터에서 비행거리가 가장 긴 데이터는 몇 마일인가

```{r}
maxDis <- max(hflights$Distance)
print(paste0(maxDis,'miles'))
```

# hflights 데이터에서 비행편이 취소된 건수는 몇 건인가

```{r}
table(is.na(hflights$Cancelled)) #NA 갯수 확인
```
```{r}
table(hflights$Cancelled)[2]
```

```{r}

```

